version: '2'
services:
    alpine_groovy:
        build: .
        container_name: scheekur_alpine_groovy
        image: scheekur/alpinegroovy
        hostname: alpinegroovy
        domainname: scheekur.devops

networks:
  default:
    external:
      name: devops
